PLAYERS_METRICS = {
    "numMinutes": "MIN",
    "points": "PTS",
    "assists": "AST",
    "blocks": "BLK",
    "steals": "STL",
    "fieldGoalsAttempted": "FGA",
    "fieldGoalsMade": "FGM",
    "fieldGoalsPercentage": "FG%",
    "threePointersAttempted": "3PA",
    "threePointersMade": "3PM",
    "threePointersPercentage": "3P%",
    "freeThrowsAttempted": "FTA",
    "freeThrowsMade": "FTM",
    "freeThrowsPercentage": "FT%",
    "trueShootingAttempts": "TSA",
    "trueShootingPercentage": "TS%",
    "reboundsDefensive": "DREB",
    "reboundsOffensive": "OREB",
    "reboundsTotal": "REB",
    "foulsPersonal": "PF",
    "turnovers": "TO",
    "plusMinusPoints": "+/-",
}
